### ISSUE TITLE
Gnome-style window controls appearance (hover and sunken effects)

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#21]
![2](https://user-images.githubusercontent.com/45201036/50460598-7be02480-0988-11e9-8574-322a21a4ed1e.gif)

In Adwaita, there is a very subtle highlight around shapes in the headerbar, which gives them a sunken effect. This is most obvious with the magnifying glass in the gif.

**Comment by kupiqu** [comment]
This may be a good opportunity for a (Gnome-friendly) person that wants to contribute to Sierra Breeze Enhanced. 

If somebody is interested I could help to get started...

**Comment by kupiqu** [comment]
Closing for lack of interest. I'm open to review a pull request

**Comment by kupiqu** [comment]
Reopening this but keeping it low priority

**Comment by kupiqu** [comment]
Button padding is implemented but this feature actually relies on (1) within-button symbol padding, and (2) rounded rectangles instead of circles (which should be applied specifically to the gnome style), only then it would make sense to replicate (3) the changes in color and gradients.

(2) and (3) seem relatively straightforward, (1) may be more tricky to accomplish.
