### ISSUE TITLE
Problem with the inactive window tittle bar color. 

### ISSUE THREAD

**Issue by boredhominid** [kupiqu/SierraBreezeEnhanced#36]
![Screenshot_20191122_131702](https://user-images.githubusercontent.com/26527950/69428995-758a3200-0d2a-11ea-8de8-98e7c2ec0987.png)

As shown in the screenshot, when a window is inactive the title bar doesn't follow the theme's color.
I'm using the AUR git build (r85.ebdab0b).

**Comment by kupiqu** [comment]
I can reproduce, thank you

**Comment by kupiqu** [comment]
Are you using `kwin auto titlebar colours` and then changed the color scheme you're using?

That's the only way I can reproduce your issue, so not really any bug here. The issue is that the script creates color schemes for those applications, and even if you change the global color scheme, these applications still follow their own.

The way to "fix" this is by doing:

```
python3 kwin_auto_titlebar_colours.py --uninstall
python3 kwin_auto_titlebar_colours.py
```

So all the new windows adapt to the new color scheme

If that is not your issue, please reopen and I will disable kwin_auto_titlebar_colours.py in my system and will try to reproduce the issue again.

**Comment by kupiqu** [comment]
Also, if you are indeed using `kwin auto titlebar colours` but want to avoid changing colors of inactive windows, you will need to modify the script. I did it and looks better to my eyes.

So this could also be the root of the issue you are experiencing (if you did not change the global color scheme), because the colors of inactive windows are also modified by the `kwin auto titlebar colours` script.

**Comment by boredhominid** [comment]
Thank you for the fast reply.
Unfortunately I do not use any third party scripts. 
However, the last commit you made fixed the problem for the most part except when I use the transparency effect for the title bar i.e. if "Opaque title bar" is checked, I get the desired outcome (both active and inactive windows use the correct theme color) else the problem is still there.
And it is kinda visible in the plasma settings preview
![Screenshot_20191122_175458](https://user-images.githubusercontent.com/26527950/69448828-594dbb80-0d51-11ea-9863-9f2f8853a690.png)
![Screenshot_20191122_175521](https://user-images.githubusercontent.com/26527950/69448829-594dbb80-0d51-11ea-8c74-a6d6c6906a27.png)

**Comment by kupiqu** [comment]
Sorry, I cannot reproduce.

Can you see if the issue is present after executing:

`kwin --replace`

I assume your color theme is not using different colors for active and inactive windows, right?

If you are still suffering the issue I need you to show me a screenshot of the General settings and a copy of your color theme.

**Comment by boredhominid** [comment]
The issue is still present after `kwin_x11 --replace`.
You're right, I'm using the same color for active and inactive title bar.

[Materia.txt](https://github.com/kupiqu/SierraBreezeEnhanced/files/3881536/Materia.txt)
![Screenshot_20191122_214225](https://user-images.githubusercontent.com/26527950/69462468-fcfa9400-0d70-11ea-8fa2-6bef1a290d57.png)

**Comment by kupiqu** [comment]
Should be fixed now. Thank you.
