### ISSUE TITLE
Title bar's color is different when separator is enabled.

### ISSUE THREAD

**Issue by arun54321** [kupiqu/SierraBreezeEnhanced#46]
![image](https://user-images.githubusercontent.com/42943340/69909719-70616d00-1425-11ea-9d8f-b180efe75beb.png)

**Comment by kupiqu** [comment]
That's intended behavior

**Comment by arun54321** [comment]
Okay. It doesn't happen on default breeze theme and sierra breeze theme.

**Comment by kupiqu** [comment]
I know. This is a change I just introduced. the Separation line in Breeze is basically invisible as there is no way you can see the blue line because of the contrast between dark and light colors.

Also, I don't see much of a point of just a line. So now more than just a line, it's all the titlebar that "prepares" the separation, with smooth but salient line in between the titlebar and the window frame.

It looks best if used with gradient. I am very satisifed in how it looks in light themes (e.g., breeze color + match titlebar to window color).

Feedback on dark themes is apreciated, but not really to come back to the previous state of a single line in the middle. Rather in creating a combination of color and gradient that makes it appealing.

Of course this doesn't have to be for everybody, one can just disable it.

**Comment by kupiqu** [comment]
Please see issue #42 for how this new concept emerged...
