### ISSUE TITLE
Thinner separator.

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#53]
I am not sure if this is deliberate but the thick 2px separator looks kind of odd to me, especially given that the window outline is 1 pixel. A one pixel separator would be more similar to what Mac OS, Breeze and Gnome use. Of course, if that's a deliberate design choice that's another matter.

Take a look at this theme - I think it gets the look just perfect : https://github.com/n4n0GH/hello

**Comment by kupiqu** [comment]
It's not just about the width of the line, it's also it's color, the gradient of the titlebar, the color of the titlebar, the color theme of the widow, whether or not the window is active or not...

My decisions are of course subjective but come from all this. In particular (but not only) I check it out with the Breeze theme with Match Titlebar to Window Color and compare how active and inactive windows look like for a gradient of 20%.

After this I decided that 2 and 1.5 px respectively for active and inactive windows is what looks better.

But certainly, if you think another theme is perfect for you, feel free to use it. 

Also, I don't think it makes much sense to replicate the same window decoration of others. My goal is to achieve a good compromise so that my themes look nice under a variety of conditions, especially titlebar colors.

**Comment by kupiqu** [comment]
I finally made this change in V0.9.1 looking for a more minimalistic title bar separator
