### ISSUE TITLE
Button Custom Size in SBE

### ISSUE THREAD

**Issue by stefanmrvic** [kupiqu/SierraBreezeEnhanced#70]
There is only tiny, small, medium, big and large button options and there is no custom button size in px.

**Comment by kupiqu** [comment]
I don't recall removing anything and this is not different from upstream official plasma breeze, at least as far as I can see. Please elaborate what you mean...

**Comment by stefanmrvic** [comment]
In the original Sierra Breeze there is a section for button size, and you could set it in px. In your version, you can only set button size by selecting few options ranging from tiny to very large. And I wanna set my button size to 6px, but i cannot.

**Comment by kupiqu** [comment]
There is a reason Sierra Breeze, Breeze Enhanced and Sierra Breeze Enhanced exist. They have some things in common but they are not tight to each other and have different goals, so each developer decides how each theme deviates (or not) from Official Breeze.

Specifically to this issue, I didn't even know Sierra Breeze sets button sizes in pixels and I consider it a feature enhancement with respect to upstream Breeze that is too minor to consider (unless you convince me otherwise, I think the benefit of the feature does not compensate the deviation from official Breeze).

So, you can try to convince me and send a pull request, or continue using Sierra Breeze, or open an issue upstream for official Breeze (if they implement the feature I will certainly port it to Sierra Breeze Enhanced).

**Comment by stefanmrvic** [comment]
Can you tell me which file controls the button size so I cananualy change it? And also, there is a bug with dolphin window color. It doesn't change, despite every other application changes window color as its supposed to. Btw, I love your project and will continue to use it regardles. Thank you for your efforts to make this better app ❤️

**Comment by kupiqu** [comment]
> there is a bug with dolphin window title bar color. It doesn't change, despite that every other application changes window title bar color as its supposed to

I don't understand, can you open a different issue for this and show this in screenshots or a gif video? are you sure you don't have a specific color theme for dolphin, or an override that can explain the difference?

> Can you tell me which file controls the button size so I manualy change it?

Using `grep -r size * | grep button` in the source code I got relevant references to breezedecoration.cpp, breezesettingsdata.kcfg, config/ui/breezeconfigurationui.ui, and config/breezeconfigwidget.cpp

I'd recommend comparing these files with those of sierra breeze (with meld/kompare/kdiff3) to filter the changes that you would need to introduce...

**Comment by stefanmrvic** [comment]
I'll check different color combinations and send you screenshoots in new issue. And thanks for the references, you rock 🌟🕺
